services:
  - type: web
    name: resume-job-matcher-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements-basic.txt
    startCommand: python -m src.main_basic
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true
