services:
  - type: web
    name: resume-job-matcher-backend
    env: python
    plan: starter
    buildCommand: ./build-no-rust.sh
    startCommand: python -m src.main_ultra_minimal
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true
