services:
  - type: web
    name: ai-resume-job-matcher
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Will be set manually in Render dashboard
      - key: DEFAULT_MODEL
        value: gpt-4o-mini
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    rootDir: .
